name: Node CI

on:
  push:
    branches:
    - master
    - staging

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
    - uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build, and test
      run: |
        npm install
        npm run start -- --testMode
        npm run demo
        npm run coverage

    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
    
      env:
        CI: true
