name: Node CI

on:
  push:
    branches:
    - master
    - staging

jobs:
  build:
    runs-on: ubuntu-latest
    
  strategy:
    matrix:
      node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use latest Node.js
      uses: actions/setup-node@v1
      with:
        node-version: latest
    - name: npm install, build, and test
      run: |
        npm install -g codecov
        npm install
        npm run start -- --testMode
        npm run demo
        npm run coverage
        codecov
      env:
        CI: true
